// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace TechReady.Portal.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SpeakerFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpeakerFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201510111117564_SpeakerFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
